version: '3.7'

services:
  redis:
    image: 'redis:latest'
    restart: always
    command: redis-server --appendonly yes
    volumes:
      - cache:/data
    ports:
      - $REDIS_PORT:$REDIS_PORT
    env_file: '.env'

volumes:
  cache:
    driver: local